- name: Get Facts
  debug:
      msg: 
        -  "ansible_lsb.major_release: {{ansible_lsb.major_release}}"

- name: install python
  apt:
      name: python
      state: present

- name: Install python-pip 
  apt:
      name: python-pip
      state: present
  # when *not* kali
  when: ansible_lsb.id != "Kali"

- name: Install python-pip-whl
  apt:
      name: python-pip-whl
      state: present
  # when *is* kali
  when: ansible_lsb.id == "Kali"

# if ubuntu 20 doesn't have python-pip or python-pip-whl, install pip2 manually
#- name: Install python-pip (Focal Fossa)
#  shell: "mkdir -p /opt/install/pip2 && curl https://bootstrap.pypa.io/get-pip.py --output /opt/install/pip2/get-pip.py && python2 /opt/install/pip2/get-pip.py"
#  when: "ansible_lsb.major_release == '20'"

- name: install python3
  apt:
      name: python3
      state: present

- name: install python3-pip
  apt:
      name: python3-pip
      state: present

- name: install python-dev
  apt:
      name: python-dev
      state: present

- name: install build-essential
  apt:
      name: build-essential
      state: present

